name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude:
    if: |
      github.actor == 'MillerBOSS' && (
        (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
        (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
        (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
        (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
      )
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
      actions: read # Required for Claude to read CI results on PRs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          prompt: |
            You are working on EyeAreSea, a macOS IRC client written in Objective-C/Swift.
            This is a fork of the Textual IRC client with specific build requirements.

            Key project details:
            - Uses Xcode workspace: Textual.xcworkspace
            - Build scheme: "Standard Release"
            - Requires code signing (configured via .xcconfig files)
            - Uses Git submodules for dependencies
            - No license manager (TEXTUAL_BUILT_WITH_LICENSE_MANAGER=0)

            When suggesting changes:
            1. Follow existing Objective-C/Swift code patterns
            2. Respect the modular XPC services architecture
            3. Consider macOS-specific requirements and sandboxing
            4. Reference the CLAUDE.md file for build instructions
            5. Be mindful this is an IRC client with networking and UI components

          claude_args: |
            --allowed-tools bash,git,xcodebuild